[project]
name = "apis"
version = "0.1.0"
description = "Various API interactions"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "opencv-python>=4.12.0.88",
    "requests>=2.32.5",
    "wget>=3.2",
]
